/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.RSA.dictionary;

import com.RSA.Excel.DictionaryBean;
import com.RSA.Excel.ExcelConnection;
import com.RSA.Excel.ExcelManager;
import com.RSA.File.Add;
import com.RSA.File.Update;
import com.RSA.Help.AboutMe;
import com.RSA.Help.Instruction;
import com.RSA.Table.SortTable;
import com.RSA.Table.TableSet;
import com.RSA.Translate.ChangeDictionary;
import com.RSA.Translate.DictionaryDataSet;
import com.RSA.Trie.B2EUpdate;
import com.RSA.Trie.E2BUpdate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sabuz
 */
public class RSA_Dictionary extends javax.swing.JFrame {

    private ExcelConnection excel;
    private SortTable table;
    private ChangeDictionary convert;
    private E2BUpdate updateEnglish;
    private E2BUpdate searchEnglish;
    private B2EUpdate searchBangla;
    
    private List<DictionaryBean> db;
    private boolean dictionarytype;
    private int previousrow;
            
            
    public RSA_Dictionary() {
        super("RSA Dictionary");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setE2BDictionary();
        dictionarytype = false;
        previousrow = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DictionaryData = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAdd = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemUpdate = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemE2B = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemB2E = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemInstruction = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemAboutMe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        txtSearch.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearch);
        txtSearch.setBounds(520, 20, 210, 29);

        lblSearch.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        lblSearch.setText("Enter English Word");
        jPanel2.add(lblSearch);
        lblSearch.setBounds(330, 24, 160, 20);

        DictionaryData.setFont(new java.awt.Font("SutonnyOMJ", 0, 18)); // NOI18N
        DictionaryData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        DictionaryData.setEnabled(false);
        DictionaryData.setRowHeight(25);
        DictionaryData.getTableHeader().setResizingAllowed(false);
        DictionaryData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DictionaryData);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 730, 550);

        jScrollPane2.setViewportView(jPanel2);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        itemAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemAdd.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemAdd.setText("Add");
        itemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddActionPerformed(evt);
            }
        });
        jMenu1.add(itemAdd);
        jMenu1.add(jSeparator2);

        itemUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemUpdate.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemUpdate.setText("Update");
        itemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(itemUpdate);
        jMenu1.add(jSeparator4);

        itemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemExit.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dictionary");
        jMenu2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        itemE2B.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemE2B.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemE2B.setText("English to Bengali");
        itemE2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemE2BActionPerformed(evt);
            }
        });
        jMenu2.add(itemE2B);
        jMenu2.add(jSeparator3);

        itemB2E.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        itemB2E.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemB2E.setText("Bengali to English");
        itemB2E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemB2EActionPerformed(evt);
            }
        });
        jMenu2.add(itemB2E);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        itemInstruction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemInstruction.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemInstruction.setText("Instruction");
        itemInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstructionActionPerformed(evt);
            }
        });
        jMenu3.add(itemInstruction);
        jMenu3.add(jSeparator1);

        itemAboutMe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        itemAboutMe.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemAboutMe.setText("About Me");
        itemAboutMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutMeActionPerformed(evt);
            }
        });
        jMenu3.add(itemAboutMe);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDictionary()
    {
        excel = new ExcelManager();
        db = new ArrayList<>();
        
        db = excel.getAllData();
    }
    
    public void setE2BDictionary()
    {
        table = new TableSet();
        
                setDictionary();
        DictionaryData.setModel(new DefaultTableModel(table.getE2BRow(db) , table.getE2BColumn()));
        
       setE2BUpdate(db);   
       setE2BSearch(db);
    }
    
    public void setB2EDictionary()
    {
        table = new TableSet();
        
                setDictionary();
        DictionaryData.setModel(new DefaultTableModel(table.getB2ERow(db) , table.getB2EColumn()));
        
        setB2ESearch(db);
    }
    
    private List<DictionaryBean> sortE2B(List<DictionaryBean> srch)
    {
        Collections.sort(srch, new Comparator<DictionaryBean>(){
        
            @Override
            public int compare(DictionaryBean x, DictionaryBean y)
            {
                   return x.getEnglishWord().compareToIgnoreCase(y.getEnglishWord()); 
            }
        
        });
        
        return srch;
    }
    
    private void setE2BSearch(List<DictionaryBean> srch)
    {
        srch = sortE2B(srch);
        searchEnglish = new E2BUpdate(-1);
        int i,sz = srch.size();
        
          for(i=0; i<sz; i++)
              searchEnglish.insertData(srch.get(i).getEnglishWord().toLowerCase().trim(), i);
         
    }
    
 private void setE2BUpdate(List<DictionaryBean> srch)
    {
        updateEnglish = new E2BUpdate(-1);
        int i,sz = srch.size();
        
         for(i = 0; i < sz; i++)
             updateEnglish.insertData(srch.get(i).getEnglishWord().toLowerCase().trim(), i);
            
    }
    
    private List<DictionaryBean> sortB2E(List<DictionaryBean> srch)
    {
        Collections.sort(srch, new Comparator<DictionaryBean>(){
        
            @Override
            public int compare(DictionaryBean x, DictionaryBean y)
            {
                   return x.getBanglaword().compareToIgnoreCase(y.getBanglaword()); 
            }
        
        });
        
        return srch;
    }
    
    private void setB2ESearch(List<DictionaryBean> srch)
    {
        srch = sortB2E(srch);
        searchBangla = new B2EUpdate(-1);
        int i,sz = srch.size();
        
          for(i=0; i<sz; i++)
              searchBangla.insertData(srch.get(i).getBanglaword().toLowerCase().trim(), i);
         
    }
    
    private int getIndex(String str)
    {
        if(dictionarytype == false)
            return searchEnglish.searchData(str);
        
        return searchBangla.searchData(str);
        
    }
    
    public int isInDictionary(String str)
    {
        return updateEnglish.searchData(str.toLowerCase());
    }
    
    
    private void itemInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstructionActionPerformed
            new Instruction(this, true).setVisible(true);
    }//GEN-LAST:event_itemInstructionActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemE2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemE2BActionPerformed
        dictionarytype = false;
        convert = new DictionaryDataSet();
        convert.E2B(this);
    }//GEN-LAST:event_itemE2BActionPerformed

    private void itemB2EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemB2EActionPerformed
        dictionarytype = true;
        convert = new DictionaryDataSet();
        convert.B2E(this);
    }//GEN-LAST:event_itemB2EActionPerformed

    private void itemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddActionPerformed
        new Add(this, dictionarytype, true).setVisible(true);
    }//GEN-LAST:event_itemAddActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
           if(previousrow>=0)
               DictionaryData.removeRowSelectionInterval(previousrow, previousrow);
        
        String word = txtSearch.getText().toLowerCase().trim();
        int index = getIndex(word);
        previousrow = index;
        
         if(index>=0)
         {
             DictionaryData.addRowSelectionInterval(index, index);
             DictionaryData.scrollRectToVisible(DictionaryData.getCellRect(index, 0, true));
         }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void itemAboutMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutMeActionPerformed
        new AboutMe(this, true).setVisible(true);
    }//GEN-LAST:event_itemAboutMeActionPerformed

    private void itemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateActionPerformed
        new Update(this, dictionarytype, true).setVisible(true);
    }//GEN-LAST:event_itemUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSA_Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSA_Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSA_Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSA_Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSA_Dictionary().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DictionaryData;
    private javax.swing.JMenuItem itemAboutMe;
    private javax.swing.JMenuItem itemAdd;
    private javax.swing.JMenuItem itemB2E;
    private javax.swing.JMenuItem itemE2B;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemInstruction;
    private javax.swing.JMenuItem itemUpdate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    public javax.swing.JLabel lblSearch;
    public javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
